# Generated by Django 2.1.5 on 2019-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0010_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.TextField(default=None, unique=True),
        ),
    ]
